### ISSUE TITLE
java.lang.illegalargumentexception

### ISSUE THREAD

**Issue by eghetto** [owntracks/android#441] opened 2017-01-15 20:52 UTC
Endpoint state message. Version 11604.

**Comment by binarybucks** [comment] 2017-01-16 12:51
You couldn't have included any less details, could you?

**Comment by eghetto** [comment] 2017-01-16 13:10
Sorry - used my phone to create the issue. It's not very convenient on the device.

However, after the update to 11604 I'm no longer able to connect. 

Status Screen  Shows: "Error / Endpoint state".

Endpoint state message: "java.lang.illegalargumentexception: myserver.com:8883:mqtt"

Is there a way to provide you with more debug information?

I'm wondering whether I'm the only one having this issue...

**Comment by binarybucks** [comment] 2017-01-16 13:13
As the error says, you've entered an invalid hostname.  For websocket connections the new version automatically appends "/mqtt" to the connect uri. Could you double check what you set as hostname int he preferences?

**Comment by eghetto** [comment] 2017-01-16 13:31
Ah thanks! - "java.lang.illegalargumentexception" is not very self-explanatory...
Well, actually I did not modify my settings/preferences. 
My hostname is set as: "myserver.com"
Port is not set.
I'm not using websockets.

**Comment by imtiajmeah** [comment] 2017-01-16 13:57
Same issue after update of the app..

**Comment by peterlozano** [comment] 2017-01-16 15:24
Same issue here. No websockers. No TLS.

java.lang.IllegalArgumentException: tcp://X.cloudmqtt:17606/mqtt

(X = my server instance)

The mqtt instance is working correctly since I'm able to connect with a different app.

**Comment by nbartels** [comment] 2017-01-16 15:25
Without changing anything the new version of owntracks is not able to connect to the mqtt broker. Append the `mqtt` should be optional ...

**Comment by binarybucks** [comment] 2017-01-16 16:25
A fix has been submitted to Google Play, it will be available shortly. Sorry for any inconvenience.

**Comment by imtiajmeah** [comment] 2017-01-16 17:23
I can confirm issue resolved. Thanks for the speedy fix.

**Comment by peterlozano** [comment] 2017-01-16 17:30
Confirmed. It works.

**Comment by eghetto** [comment] 2017-01-16 17:38
Agree, issue solved! Thank you!

**Closed** 2017-01-19 10:48 UTC
Labels: triage
