### ISSUE TITLE
Can't get setwaypoints to work

### ISSUE THREAD

**Issue by Botched1** [owntracks/android#803] opened 2020-03-23 19:58 UTC
I am at a loss. I'm sure it is just something I'm doing wrong, but for the life of me I can't figure out what!

I have 4 android devices setup via MQTT. Location updates are coming in just fine - which is great! I have verified that Remote Commands are enabled on all devices.

I am trying to publish some new regions (waypoints). But nothing ever happens on the phone.

My MQTT:
![image](https://user-images.githubusercontent.com/19985320/77357674-8bc6ef80-6d16-11ea-9e4f-64626c4dd704.png)

I am publishing the following to owntracks/Jason/Note10/cmd (is that the right place?? The booklet doesn't actually say WHERE to publish the JSON as far as I can tell).

What I'm trying to publish:

```json
{
	"_type": "cmd",
	"action": "setWaypoints",
	"waypoints": {
		"waypoints": [{
			"desc": "Clark",
			"rad": 300,
			"lon": -98.580967,
			"lat": 29.565631,
			"tst": 1584991766,
			"_type": "waypoint"
		}],
		"_type": "waypoints"
	}
}
```

**Comment by growse** [comment] 2020-03-23 20:03
Entirely possible this is a bug. I know that waypoints created by other devices that get pulished to `/waypoints` on MQTT, but haven't recently explicitly tested the `setWaypoints` command.

**Comment by jpmens** [comment] 2020-03-23 20:07
@Botched1 the topic you are posting to corresponds to what we’ve documented at the top of the JSON page of the Booklet, so that looks fine.

One small nit: in the `wayponts` array you are specifying a `_type`; this is superflous, however I assume we ignore it.

Are you publishing with QoS>0 to make sure the device gets your publish?

**Comment by Botched1** [comment] 2020-03-23 20:07
I published it as QOS 2.

**Comment by Botched1** [comment] 2020-03-23 20:09
> One small nit: in the `wayponts` array you are specifying a `_type`; this is superflous, however I assume we ignore it.

I used the example from the booklet, which included _type:
https://owntracks.org/booklet/features/remoteconfig/

**Comment by jpmens** [comment] 2020-03-23 20:15
Apologies: I checked simultaneously: you are right: the `_type` is required.

**Comment by Botched1** [comment] 2020-03-23 20:19
> Apologies: I checked simultaneously: you are right: the `_type` is required.

No worries at all!

Also, I didn't put it in my original post, but I am using android app 2.1.3 (21302).

Thanks again!

**Comment by growse** [comment] 2020-03-24 17:21
Hmm, so I tested it on the emulator both on `master` and `2.1.3` and I can't reproduce. Sending an MQTT message like the one in the booklet:

```
mosquitto_sub ... -m '{"_type":"cmd","action":"setWaypoints","waypoints":{"waypoints":[{"desc":"Some place","rad":8867,"lon":10.428771973,"lat":46.935260881,"tst":1437552714,"_type":"waypoint"}],"_type":"waypoints"}}' -t 'owntracks/powerswitchbots/testdevice/cmd'
```

Gives me a region on the device:

![device-2020-03-24-172109](https://user-images.githubusercontent.com/378067/77456933-df5b3b00-6df3-11ea-9d00-b3344f4e2334.png)

**Comment by jpmens** [comment] 2020-03-24 18:12
@Botched1 can you please try this again and from the command line subscribe to the topic you are posting to and verify the payload is in fact what you think it should be?

```console
$ mosquitto_sub -h hostname ... -v -t owntracks/Jason/Note10/cmd
```

What might also help is the log of your broker during that publish.

**Comment by Botched1** [comment] 2020-03-24 19:33
OK. I'm extremely embarrassed.

I have bridged MQTT - external on Linode, internal for local MQTT use.

I was publishing the cmd on my internal MQTT server.... :/  So obviously it never made it to the external (one way bridge).

Sorry for wasting people's time!!!!

**Comment by jpmens** [comment] 2020-03-24 19:46
Things like that happen; thanks for confessing :-)
I’ll close this now, but please don’t hesitate to report back if you have trouble.

**Closed by jpmens** 2020-03-24 19:46 UTC
