### ISSUE TITLE
 build 21301 and websockets causes reconnect loop

### ISSUE THREAD

**Issue by tsheldon** [owntracks/android#699] opened 2019-03-11 18:28 UTC
Just had build 21301 pushed from the play store and my connection immediately started looping.

I use cloudmqtt with websockets as my broker.  When I disable websockets and drop back to using the ssl port the connection remains stable. 

I'll attach a relevant debug log once I sanitize it a bit.

* **App build number**: 21301
* **Android version**: 9 
* **Device**: Google Pixel 3 XL

**Comment by binarybucks** [comment] 2019-03-11 18:33
Can you check if this is a duplicate of https://github.com/owntracks/android/issues/697? In any case a debug log will be helpful.

**Comment by tsheldon** [comment] 2019-03-11 18:40
Unfortunately I can't tell if it's a duplicate since I don't have the main logs from cloudmqtt-  I've attached the relevant lines from the debug log following where I changed the port and websocket toggle and the crashes started.

The sanitized "<host:port>" is the expected host:port combo for my cloudmqtt instance and doesn't reference port 80.
[11-03-2019.txt](https://github.com/owntracks/android/files/2953730/11-03-2019.txt)

**Comment by binarybucks** [comment] 2019-03-12 19:24
I can reproduce the reconnect loop. 
Might be related to https://github.com/owntracks/android/issues/699 
WS connections with Paho 1.2.0 seems to work fine

**Comment by binarybucks** [comment] 2019-03-20 10:39
Downgraded library in ae12f77c03f81910b435df01dc1e3446361032cf. Fix will be in next release.

**Closed by binarybucks** 2019-03-20 10:39 UTC
