### ISSUE TITLE
OwnTracks crashing when holding backspace in the coordinate fields when creating waypoint.

### ISSUE THREAD

**Issue by Unkn0wnCat** [owntracks/android#776] opened 2020-01-15 16:03 UTC
Hello OwnTracks contributors,

When holding backspace on the virtual keyboard (SwiftKey Beta in my case) in the latitude or longitude field of the add waypoint dialog the app crashes. Just tapping backspace works just fine.

* **App build number**: 21302
* **Android version**: 10 (Oxygen OS 10.0.7.HD65BA)
* **Device**: OnePlus 7T

A mate of mine who uses the OnePlus 6 (Android 10 as well, using stable SwiftKey) is experiencing the same problem.

Best regards,
Kevin

**Comment by growse** [comment] 2020-03-06 18:11
If this is the bug I'm thinking of, I *believe* this was fixed by https://github.com/owntracks/android/pull/752 - but not sure if we've had a release since then.

Certainly running HEAD on the emulator, I can't reproduce this.

**Closed** 2020-03-06 18:12 UTC
Labels: bug
