### ISSUE TITLE
Crash when exiting Android 7.0 split screen mode

### ISSUE THREAD

**Issue by juzam** [owntracks/android#427] opened 2016-11-16 11:02 UTC
I have managed to crash the app when exiting split screen mode, dragging the slider in order to restore Owntracks in full screen.

I didn't have time to catch the subimt crash dialog, nor i've been able to reproduce it so far.

**Comment by jpmens** [comment] 2016-12-14 21:16
@juzam if you cannot reproduce, can we close this?

**Comment by juzam** [comment] 2016-12-14 21:46
Yes,  no problem. I'll reopen it if needed.

Il mer 14 dic 2016, 22:16 JP Mens <notifications@github.com> ha scritto:

**Closed** 2016-12-14 21:46 UTC
