### ISSUE TITLE
Can I get the old Android reporting method back?

### ISSUE THREAD

**Issue by x99percent** [owntracks/android#648] opened 2019-01-04 19:23 UTC
I was using remote configuration for my Owntracks config to control reporting frequency. Now, it seems that the Android version is using the same 4 reporting options as the iOS version, so my remote config changes aren't having an effect.

**Comment by x99percent** [comment] 2019-01-04 20:41
It's not working at all like it used to. With 300 seconds showing in my OwnTracks config, I'm getting location updates every 20-30 seconds.

**Comment by jpmens** [comment] 2019-01-04 22:12
You are maybe seeing what we call "pings"; what is the value of the `"t"` element in the JSON payload you see?

**Comment by x99percent** [comment] 2019-01-04 23:51
There isn't a "t" element?

Each message is a location update with varying accuracy, latitude, and longitude.

**Comment by binarybucks** [comment] 2019-01-05 13:15
If there‘s no `t` element, the report is triggered by an updated location that the app received from the OS. In significant location changes mode, Owntracks requests updates with a interval/displacement that can be set from the user. Location updates (and hence location reports) might be received faster, if another app also requests location updates. If you e.g. have Google Maps open, fast GPS location updates will be reused. If there‘s no other app running, that also requested fast location updates, there‘s something wrong or the mode somehow got stuck (judging from 20-30s interval the app might still be using a location request from move mode). 

Please keep in mind that the configurable interval is not a fixed one. Updates might be received faster if they‘re available. The intarval is only an upper limit in which a location update should be available. 

@x99percent please do the following: 
1) check if another app is requesting the location and if e.g. GPS is requested by something(location pin in bar) 
2) check if Owntracks is in significant location changes mode. If so, force quit Owntracks and start again. If still receiving fast updates, restart phone and restart Owntracks to clear a possibly stuck Android location request.

**Comment by apkent23** [comment] 2019-01-07 20:36
Afraid I'm also having the same issue with 20-30 second updates IF MOVING.

HTTP mode on a Huawei P20 lite (android 8).
Displacement manually set to 500
Interval manually set to 300. 
I believe the app is set to significant changes mode (3 in config?)
I have android auto running on the phone when connected to car bluetooth. 

Today I was in the office most of the day so I got a "t":"p" every half hour or so which is fine. As soon as I got in the car this morning the server was fired an updated about every 15 seconds or so with no "t" flag. 

I thought interval was the limiting factor?

**Comment by binarybucks** [comment] 2019-01-07 20:40
If you’re e.g  navigating with Android Auto it will provide new locations to Owntracks which will publish them. 

As stated above the interval guarantees location updates roughly at least every interval.

**Comment by binarybucks** [comment] 2019-01-07 20:41
May I ask what the issue is with too many updates? In previous versions everyone was complaining about not enough updates

**Comment by apkent23** [comment] 2019-01-07 21:09
Ha, you just can't win can you!

Ok, thats fair enough. In that case perhaps this could be made clearer in the booklet? The booklet says the opposite - https://owntracks.org/booklet/features/location/

> The way it currently works is by specifying an interval in which you want to receive updates (the one you configure in the settings). **You only receive updates if this amount of time has passed** and you moved more than 500m (when the app is in the background. The movement restriction is set to 50m or so when in the foreground).

On the face of it more updates isn't an issue provided battery life isn't being sacrificed. For my personal use I'll end up binning most of the data hence my focus having been on battery life.

**Comment by x99percent** [comment] 2019-01-09 22:14
The behavior as outlined in the booklet is **exactly** how it used to work, and **exactly** what I want. Right now, OwnTracks updates when it wants to, with seemingly no regard to the configured interval. 

- Why am I getting updates every 20-30 seconds while moving, when my interval is set to 10 minutes??
- Also, why am I **not** getting updates quickly when my interval is set to 5s and the displacement is set to 10m?
- Is there a hard minimum/maximum set for time between updates?
- Why isn't the app using GPS when I open it to get a better fix, like it used to?

I'm using OwnTracks as part of the puzzle for presence detection. Using remote config, I ramp up updates as I get closer to home, and slow them **way** down as I move away. I've got logic in my automation to dumb down the updates when I'm home. In its current state, OwnTracks updates when it feels like updating, often leaving an inaccurate location if I don't move far enough away from the "bad" update.

If people were unhappy with "not enough updates", they should have been directed to examine their OwnTracks configuration. As it was, OwnTracks worked just fine.

Can I download the old APK somewhere?

**Comment by markrennie71** [comment] 2019-01-10 13:44
> May I ask what the issue is with too many updates? In previous versions everyone was complaining about not enough updates

I hated the thought of not having iBeacons in Owntracks but I am running it in "move mode" and it is working a treat.. almost as soon as I enter a zone, boom it is registered in HA, so that you for all the work on this..

**Comment by binarybucks** [comment] 2019-01-10 13:55
@markrennie71 thanks for the kind words. 2.x also contains new code that checks if a lcoation update is inside or outside a region. So even if the OS geofence API didn't catch a transition, the location update will trigger a region event. 

@x99percent regarding your questions. 
* Why am I getting updates every 20-30 seconds while moving, when my interval is set to 10 minutes??
The interval is not the reporting interval. It is called locator interval for a reason. It defines, as stated many times before, the maximum interval between location updates provided by the OS to the app. If updates are available earlier because e.g. Google Maps requested a position, Owntracks will publish them.

*  Also, why am I not getting updates quickly when my interval is set to 5s and the displacement is set to 10m?
Because then updates are limited by two parameters, interval and displacement. It is a bit tricky and not very well documented by Google how a location request with both parameters works. I assume that a location update will be received if the device moved displacement meters in interval seconds. There also appears to be some capping for too low values.  Pre 2.1 Owntracks versions had a default displacement. With 2.1 we default displacement to 0 because that generally increases the number of location reports. If you want pre 2.1 behavior back, you should run signifficant mode with interval and displacement (old default was 500m I think).

* Is there a hard minimum/maximum set for time between updates?*
Owntracks will not receive updates faster than every 10s. This is hardcoded to the location request. 

* Why isn't the app using GPS when I open it to get a better fix, like it used to?
This required us to newly request location updates everytime the app changed from foreground to backgorund and vice versa. This often confused the location APIs and broke things until the phone was restarted. Hence we got rid of it to reduce the number of location requests. 

That being said, the 20-30s interval matches the hardcoded 30s interval for the monitoring mode location request. I think that your app is either in move mode or the location request got stuck. Hence my two questions above to verify which were still not answered.

**Comment by x99percent** [comment] 2019-01-10 18:23
I edited my post above, from 6 days ago. My issues with "significant changes mode" still remain.

> If you want pre 2.1 behavior back, you should run signifficant mode with interval and displacement (old default was 500m I think).
That's **exactly** what I'm trying to do, and it is not working as expected. I've force closed the app, restarted my device, etc., etc., etc. OwnTracks **is** behaving somewhat as you've described, but that doesn't fully explain the all of weirdness I'm seeing (frequent updates when I don't want/need them just because I'm moving, and slow response when I do want fast updates). You've kinda reversed the logic from how it has been described in the documentation for quite some time. Again, if people were complaining about a lack of updates, they should have been directed to examine their configuration.

For now, I've gone back to OwnTracks 1.2.7, and it works perfectly. My battery seemed fare better overnight as well.

**Comment by x99percent** [comment] 2019-01-10 18:30
> Btw in significant mode with both parameters set, the location request code is exactly the same as before. 

It can't be, because I'm getting 20-30 updates while moving if my interval is set to 10 minutes.

**Comment by binarybucks** [comment] 2019-01-10 18:33
The interval is not relevant here. It just means that you get updates *at least* every 10 minutes.

**Comment by x99percent** [comment] 2019-01-10 18:42
Again, I will point to the documentation, as well as how the program used to work before 2.X. You have changed the app and reversed the logic.

**Comment by binarybucks** [comment] 2019-01-10 18:44
Yes you pointed that out enough times.
Can you provide me the mentioned debug log file so I can have a look and troubleshoot or would you like me to close this issue?

**Comment by x99percent** [comment] 2019-01-10 19:38
Here's where I'm at: 

The pre-2.X app works as expected. In the current version, the logic around the locatorInterval is reversed, and seemingly for bad reasons (users that didn't config properly for their needs). Because of those changes, the current version of the app arguably uses more battery, providing frequent location updates when those updates are not desired or needed (I set a large interval for a reason, but the app no longer respects that because I happen to be moving).

I would be happy to help debug the application, but **please** put the logic around the locatorInterval back to the way it was. People looking for more frequent updates should be directed to properly utilize the configuration options.

**Comment by binarybucks** [comment] 2019-01-10 19:53
I’ll explain it one last time. We didn’t reverse any logic and there isn’t much magic involced. To get location information we request location updates from the Android location API. This location request has several parameters with the most prominent being interval and displacement. On previous versions there was a background location request and a foreground location request. Parameters of the background location request could be tweaked with interval and displacement from the preferences. The foreground location request used hard coded values with a low displacement/interval and a high power location source.

In the new version the forgeground request was removed. The background request code was taken and used for the significant location mode. Around that we added three other modes with hard coded interval/displacement/location source. 
The actual code to request things in significant mode is exactly the same as in the previous version. The only thing that did change was the default value for displacement (500->0), publishing updates as fast as the phone provides them.

Again, we didn’t invert any logic because there really isn’t any. 

If you set the displacement to >0 

What COULD happen is that the app gets stuck in a wrong mode (e.g move mode) which uses different location request parameters. This should be visible from the debug logs.

**Comment by jpmens** [comment] 2019-01-10 20:08
@x99percent please provide the requested debug log..

**Comment by x99percent** [comment] 2019-01-10 21:33
I will re-test later and report back. I **do** have a locatorDisplacement value set, and that value (along with the locatorInterval) can be rather large if I am far away from home. I set both interval and displacement with every config change. The values used are based on how far away I am (battery-saving effort + trying to avoid useless data).

> @x99percent please provide the requested debug log..
Where is that accessed in the app?

**Comment by jpmens** [comment] 2019-01-10 21:46
https://owntracks.org/booklet/features/android/#debug-log

**Comment by jpmens** [comment] 2019-01-11 06:57
When you submit your debug log, please also submit your settings to support@owntracks.org after redacting passwords.

**Comment by x99percent** [comment] 2019-01-13 19:57
Think I've figured it out. The current version accepts remote config changes, but those changes don't always take effect. For example, I ramp up the interval and displacement to as high as 600/2400 when I'm far away from home, but I'm still getting updates every 10-30 seconds.

It's hard for me to get this in a debug log, because turning on the log means restarting the app.

**Comment by binarybucks** [comment] 2019-01-13 20:00
True, the location request isn’t requested again on remote config changes. It also wasn’t on the previous version though. 

Regarding the log, can you not just keep it enabled?

**Comment by x99percent** [comment] 2019-01-13 20:16
Requested again?

I would just expect that remote config changes would actually take effect... otherwise, what's the point?

**Comment by binarybucks** [comment] 2019-01-13 20:32
Some options are applied immediately, some are not. Right now there’s a huge number of options and making every single one changeable at runtime would add a significant amount of complexity. 

To be honest you’re the first user changing locator settings on the fly.

**Comment by x99percent** [comment] 2019-01-14 01:40
Version 1.2.7 applies the changes on the fly. 

OwnTracks reports location.
MQTT config sent.
OwnTracks reports location again, 2-3 seconds later. Plus future updates use the new interval/displacement.

**Comment by binarybucks** [comment] 2019-01-14 05:39
1.2.7 had indeed a listener for locator config changes. It must have gotten removed with 2.x. 
It’s easy to add again so consider that fixed in the next version.

**Closed** 2019-01-15 05:42 UTC
