### ISSUE TITLE
No subjectAltNames on the certificate match

### ISSUE THREAD

**Issue by kr3o** [owntracks/android#896] opened 2020-12-23 09:30 UTC
* **App build number**: 2.2.1 (22126)
* **Android version**: 10
* **Device**: Samsung Galaxy S9

Using MQTT TLS with self signed certificate for a few years now and after latest update I get the error of subject.

No subjectAltNames on the certificate match

Nothing else changed and I can connect fine to the Broker from the same phone from other apps (same cert) and from other phone from not-updated Owntracks version..

**Comment by tiger42** [comment] 2020-12-24 12:14
I've got exactly the same problem after updating the app.

**Comment by growse** [comment] 2020-12-24 12:17
This one came up in testing, and I thought we'd squashed it. Evidently not. 

Can you confirm:

1. How many SANs are present on your server cert?
2. Is the certificate CN included in the SAN list (if non-zero length)
3. Are you connecting to the broker using the hostname listed in the CN?

**Comment by tiger42** [comment] 2020-12-24 12:42
I hope that I've interpreted the output of the openssl command correctly:

> 1. How many SANs are present on your server cert?
none

> 2. Is the certificate CN included in the SAN list (if non-zero length)
-

> 3. Are you connecting to the broker using the hostname listed in the CN?
No, it's a different hostname. The CN contains the hostname for my local network. The public hostname (reachable via Internet) is different.

**Comment by kr3o** [comment] 2020-12-26 09:55
Also from my setup

> This one came up in testing, and I thought we'd squashed it. Evidently not.
> 
> Can you confirm:
> 
> 1. How many SANs are present on your server cert?

Single host name, no alternate names

> 2. Is the certificate CN included in the SAN list (if non-zero length)
> 3. Are you connecting to the broker using the hostname listed in the CN?

Issue happens in all cases, also from the internet to the hostname listed in the cert and from local network...

**Comment by growse** [comment] 2020-12-26 11:43
Do you know what version of TLS the MQTT broker is configured with?

**Comment by tiger42** [comment] 2020-12-26 17:36
My MQTT broker (Mosquitto 1.6.12) is configured to use TLS 1.2 only.

**Comment by kr3o** [comment] 2020-12-27 11:53
I am using Mosquito 1.5.7 configured with no specific version restrictions (allowing TLS 1.2 and 1.3 by default to my knowledge)

**Comment by growse** [comment] 2020-12-27 17:29
Ok, I've been slightly down the rabbit-hole on this one. It looks like that the current Google Conscrypt implementation explicitly requires the server hostname to be listed in the SAN list on the cert: https://github.com/google/conscrypt/blob/d61af15/common/src/main/java/org/conscrypt/OkHostnameVerifier.java#L126.

There's some history here. Using CN to validate the server hostname has technically been depreceted for over 20 years now (https://tools.ietf.org/html/rfc2818#section-3.1). RFC6125 then updated that back in 2011 to remove the requirement for clients to even check the CN, and Chrome itself removed CN checking back in 2017. So it's entirely following the standard for the conscrypt library to only check the SAN fields, which is a change they seemingly made back in August.

There's two paths here. One is that we try and maintain a custom host verifier in the codebase that implements long-deprecated functionality. The other is that we don't and verification based on the CN stops working, in line with the deprecation.

I'm not really inclined to write and maintain code that's security-critical, so I'm leaning towards the latter. Tools like `mkcert` (https://github.com/FiloSottile/mkcert) already do the right thing when generating self-signed certificates, so I'd encourage their use in this case.

**Comment by nwf** [comment] 2020-12-27 17:52
Argh, I was just bitten by this myself.  Having been given the leaf certificate of the remote endpoint, it is *completely and utterly unnecessary* to check the DN or SANs, so long as the *keys* match; please at least add a configuration option to disable hostname verification completely while preserving certificate *key* verification (it's also probably a good idea to continue to check certificate lifetime, too).

**Comment by growse** [comment] 2020-12-27 18:30
> Argh, I was just bitten by this myself.  Having been given the leaf certificate of the remote endpoint, it is *completely and utterly unnecessary* to check the DN or SANs, so long as the *keys* match; 

Not sure I 100% follow. Are you saying that if the client is explicitly given a CA cert to use, then the hostname verification can be unnecessary?

**Comment by nwf** [comment] 2020-12-27 18:55
> Oh, I just read the mosquito issue. I _think_ what you're saying is that if the provided certificate as the CA is identical to the leaf presented by the server, there's no point verifying the hostname. Is that right?

That's correct.

**Comment by growse** [comment] 2020-12-27 19:24
I see. I'm still leaning on the side of writing less code and having fewer options rather than more.

What's the scenario or use-case where it's better to have this implemented in the app, rather than just generating certs with SANs?

**Comment by nwf** [comment] 2020-12-27 20:16
I have a dozen different network paths that all reach my MQTT broker; there's absolutely no reason that the broker or its certificates need to be aware of all of them.

**Comment by growse** [comment] 2020-12-27 21:06
I guess wildcard won't work, because most implementations disallow too-liberal wildcarding.

So we can consider this to be a feature request to allow the user to disable hostname checking if the specified CA is the same as that provided by the server. I'll have a think about how best this might be achieved with the least amount of overhead and complexity.

**Comment by nwf** [comment] 2020-12-27 22:21
Even just a "disable hostname checking" tick-box option would be fine, perhaps with some warning text about being sure the user controls the CA.

**Comment by avanc** [comment] 2020-12-29 09:56
Same Problem here with Let's encrypt certificate after last update.

**Comment by growse** [comment] 2020-12-29 11:34
> Same Problem here with Let's encrypt certificate after last update.

Does your cert have any SANs present?

I'm using Letsencrypt and the latest version without specifying anything special on the client side without a problem. The cert my broker is using is configured shows that Letsencrypt adds the SAN correctly:

```
$ openssl s_client -connect mqtt.host.com:8883 </dev/null 2>/dev/null | openssl x509 -noout -text
...
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
        Validity
            Not Before: Oct 19 15:54:47 2020 GMT
            Not After : Jan 17 15:54:47 2021 GMT
...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                BB:A6:44:F4:29:8A:D1:D8:B8:34:59:C2:BC:F9:B8:2D:40:28:3A:9A
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:host.com, DNS:mqtt.host.com
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
```

**Comment by avanc** [comment] 2020-12-29 12:56
@growse Thanks for the hint. My certificate was missing the host.com domain, as I directly connect to it. As www.host.com was available, previous versions of Owntracks didn't complain.

**Comment by jhettler** [comment] 2020-12-29 23:04
Just in case someone wants to regenerate certificates (for Mosquitto) with SAN (subject alternative names) https://gist.github.com/jhettler/f7166d2f2f004874e3a73e4dd972131e. It is more or less sequence of commands then a bash script. I am definitely not a certicate guy, so comments are welcome.

**Comment by growse** [comment] 2020-12-30 00:49
> Just in case someone wants to regenerate certificates (for Mosquitto) with SAN (subject alternative names) https://gist.github.com/jhettler/f7166d2f2f004874e3a73e4dd972131e. It is more or less sequence of commands then a bash script. I am definitely not a certicate guy, so comments are welcome.

Thanks for this - useful to see the steps needed when using openssl itself.

As I mentioned at the start of the thread, there's also some alternative good tooling (I use https://github.com/FiloSottile/mkcert) that can very quickly and easily generate certificates with whatever hostnames you like, and are about as "zero-config" as you can get.

**Comment by kr3o** [comment] 2021-01-03 12:16
Well, that's all good and nice, but no matter if some ill code was inherited or produced, the result is that we had a working app and now it does not work...
Producing new certificates is quite a trouble since way too many clients -that actually work just fine as they are‐ will have to be reconfigured...
The workaround of a "don't validate server" checkbox in the configuration would be much preferable and it would actually bring back the functionality that was in place up to now...

**Comment by jpmens** [comment] 2021-01-03 12:31
The Changelog for 2.2.2 explains this very clearly:

> This is in line with the deprecation of using CN for host verification as of RFC2818 (2000) and RFC6125 (2011). Instead, hostnames will be validated against the list of subjectAltNames (SANs) in the server certificate.

We've been doing it incorrectly for very many years and have now fixed it.

Producing a new certificate is quite trivial actually, and for people who've deployed their own CA (something which sounds bombastic [but needn't be](https://github.com/owntracks/tools/tree/master/TLS)) and have deployed the CA certificate to their devices there will be no reconfiguration needed.

**Comment by growse** [comment] 2021-01-03 12:36
> Well, that's all good and nice, but no matter if some ill code was inherited or produced, the result is that we had a working app and now it does not work...
> Producing new certificates is quite a trouble since way too many clients -that actually work just fine as they are‐ will have to be reconfigured...
> The workaround of a "don't validate server" checkbox in the configuration would be much preferable and it would actually bring back the functionality that was in place up to now...

Your "working app" was depending on behaviour that's been deprecated since at least 2011, arguably since 2000. Chrome removed this back in 2017. Golang dropped it in v1.15. The world is moving on.

I really don't think that writing new code (and therefore introducing new bugs), especially in the TLS/security domain to perpetuate the use of deprecated behaviour is a good idea.

**Comment by nwf** [comment] 2021-01-03 15:19
> If you don't want to validate the server hostname, why are you even using TLS?

In my case, because I want to validate the *server's public key*, and unfortunately TLS with X.509 is essentially all of that we have at scale.

To be glib for a moment... I don't see OwnTracks and Mosquitto growing support for, for example, SSH's transport layer or QUIC any time soon, do you?  Similarly, while TLS-the-protocol nominally supports things aside from X.509---RFC6091 for PGP keys, RFC5489 for ECDHE_PSK, &c---those are also not available at scale.

In any case, there are cases where it is sensible to disable the entire X.509 notion of *naming* without compromising cryptographic integrity.  I think there are three principled approaches available:

* a "disable hostname checking" tickbox along the lines of Mosquitto's CLI's (dramatically named) `--insecure` option.  This probably requires very little TLS-domain code; many libraries make this fairly easy.  In Conscrypt, it looks like it might merely be a matter of providing `setDefaultHostnameVerifier` (https://github.com/google/conscrypt/blob/23c2ce258afd5a43258b685df4279eaa2ee0e15c/common/src/main/java/org/conscrypt/Conscrypt.java#L762) a stub implementation of a `ConscryptHostnameVerifier` that just returns true.  If the `TrustManager` is directly exposed to OwnTracks (it might well not be), this could be set per-TrustManager rather than for all of Conscrypt, but I think is is not terribly significant.

* The above, but also requiring the server's public key to exactly match that of the provided CA certificate.  This further guts the X.509 notion of naming and is likely moderately safer -- you can't accidentally land the LetsEncrypt CA cert and still get a connection to your broker, for example -- but will likely require more TLS-domain code, since the TLS libraries generally really want to do the X.509 certificate chaining logic themselves, and Conscrypt appears to be no exception to this.

* Optionally disable X.509 verification entirely and just verify the remote endpoint's public key directly, possibly even by taking its SHA256 fingerprint in lieu of a certificate in configuration.  This is probably yet further surgery into TLS, but it would be the tightest implementation of the requirement.  I have not looked at whether or how Conscrypt would facilitate this.

**Comment by kr3o** [comment] 2021-01-03 16:15
just as nwf said..
Cryptography is needed. Host is known and validated by the key..
Goggle/Crome may have it as so since for ever but they had the option "add exception" since day one!! How can you argue about the necessity of this??

**Comment by growse** [comment] 2021-01-05 17:28
I've had time to get a tiny bit of sleep on this, and I think we're at slight cross-purposes. There's actually two separate issues here, which are related but different. The first is around whether or not `CN` is considered a valid field to check when verifying hostnames - the position I've been arguing from is that this is now deprecated and won't be supported going forward. I had mistakenly assumed that people who were experiencing failures in the most recent versions had simply had an issue with using self-signed certs which weren't setting the SANs.

However, there's a separate issue around doing hostname verification at all on self-signed certs. Having done a bunch of testing, there's a regression here as well, where the Android platform verifier (used pre-2.2.1) skipped this for self-signed certs, whereas the conscrypt Trustmanager doesn't. Apologies, I should have tested that case earlier, as I didn't realise there was a regression here as well. Chalk it up to too-much-going-on-at-once.

Having spoken with a bunch of people who are much smarter than me, it seems like while it's not endorsed by the standard, setting the CA certificate field to be the same as the server leaf is effectively pinning that certificate and therefore there's not much value in doing the verification. 

@nwf I think there's a 4th implementation option, which is for a custom `HostnameVerifier` to first check to see if the server leaf cert fingerprint matches that of the client-supplied CA cert. If there's a match, then it skips any further checks and returns `true`. If not, then it defers to the RFC 2818-compliant verifier (`OkHostnameVerifier`). Does that approach look like it'd work?

**Comment by nwf** [comment] 2021-01-05 18:09
That sounds completely viable if the `HostnameVerifier` has access to the server leaf cert and the provided one.

**Comment by GForce2010** [comment] 2021-01-21 17:11
I have just replaced my phone so setup the latest version of Owntracks and I am now getting this error. 

I don't know a great deal about SSL and certificates, I only managed to set it up in the first place by following a tutorial online. 

Would someone be able to explain or link to a tutorial on how to generate new certificates with the necessary fields populated?

Thanks.

**Comment by growse** [comment] 2021-01-23 16:17
> 
> 
> I have just replaced my phone so setup the latest version of Owntracks and I am now getting this error.
> 
> I don't know a great deal about SSL and certificates, I only managed to set it up in the first place by following a tutorial online.
> 
> Would someone be able to explain or link to a tutorial on how to generate new certificates with the necessary fields populated?
> 
> Thanks.

As above, I'd personally just look at using a tool like `mkcert` which can take care of generating an appropriate CA and signed certificate with as many / whatever hostnames you require. Then you just need to configure the MQTT server with the CA/Server certificate, and configure the Android app with the CA cert that `mkcert` generates as the trusted root CA for the connection.

The README on the `mkcert` repo is pretty easy to follow: https://github.com/FiloSottile/mkcert

**Closed** 2021-01-23 20:11 UTC
Labels: enhancement
