### ISSUE TITLE
Preferences.java line 36

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#121] opened 2015-03-17 19:27 UTC
#### in org.owntracks.android.support.Preferences.getBoolean

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5508801f5141dcfd8f26a290](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5508801f5141dcfd8f26a290)

**Comment by binarybucks** [comment] 2015-03-18 09:50
duplicate of #122

**Closed by binarybucks** 2015-03-18 09:50 UTC
