### ISSUE TITLE
Owntracks does not reconnect when switching networks

### ISSUE THREAD

**Issue by syphernl** [owntracks/android#492] opened 2017-06-10 10:01 UTC
This seems to be a problem that started recently. In the past, switching from WiFi to 4G/3G and back worked just fine. 

The app reports an error, but doesn't appear to be reconnecting if it is not connected anymore.

This is on a Nexus 5X with Android 7.1.2 and the latest version of Owntracks from Google Play.

**Comment by binarybucks** [comment] 2017-06-10 10:03
Owntracks is not yet supported on Android 7.1.2 due to many breaking changes what apps can do in the background. There is a lot of work being done on in https://github.com/owntracks/android/tree/f_background_scheduler to fix this.

**Comment by syphernl** [comment] 2017-06-10 10:11
Hmm, it was working fine for me on the precious version of Owntracks. The latest update seems to have introduced this issue.

Hopefully reducing the keepalive period from 3600 to 300 helps in connection recovery.

**Comment by binarybucks** [comment] 2017-06-10 10:13
The keepalive period does not influence the reconect interval. It does just make the app use more battery ;)

**Comment by binarybucks** [comment] 2017-06-10 10:15
Please post the full build number from Preferences/Information

**Comment by syphernl** [comment] 2017-06-10 10:46
Good to know about the keepalive, I have reset it to the default (3600)

The version/build is 1.2.3 (12304)

**Comment by syphernl** [comment] 2017-06-10 12:59
The Endpoint State message shows the following message in case it is disconnected again:
```java.langException: Connection lost (32109) - javax.net.ssl.SSLException: Read error: ssl=0xc90d1780: I/O error during system call, Software caused connection abort```

**Comment by binarybucks** [comment] 2017-06-10 13:10
That's the general message when the broker connection is lost due to network failover, broker restart, etc.

**Comment by mcnewton** [comment] 2017-06-22 14:38
Just as another data point I installed OwnTracks 1.2.3 (12304) on Motorola Moto X Android 6.0.1 for the first time a couple of days ago, and I see the same. Working on 4G, then move to wifi (where tcp/8883 is blocked) the connection is lost. Move back to 4G and it takes ages before it realises that there is a new connection and tries again. Don't know if expected behaviour is to see that the network connection has changed and then immediately try to reconnect, but that is what I thought would happen.

Also on wifi the Status screen shows Endpoint queue "0", but when you force a reconnection on 4G again it uploads a load of points, so there definitely was something in the queue. Maybe the number displayed there is not being displayed correctly?

**Comment by binarybucks** [comment] 2017-06-22 14:41
The queue number is not updated in the version, this is a known bug that will be fixed soon. 
The app cannot react to network changes but currently tries to reconnect in exponential intervalls starting at 30s and capped at 16m. 

If you need more robust handling of network loss, please use HTTP mode. 

The next versions will handle this differently.

**Closed** 2017-07-01 11:56 UTC
