### ISSUE TITLE
Build 21301 fails to connect to SSL MQTT

### ISSUE THREAD

**Issue by syphernl** [owntracks/android#695] opened 2019-03-06 07:13 UTC
I was part of the beta of OwnTracks on the Play Store. 
After the update of yesterday, my OwnTracks client ceased working immediate. 
It simply wouldn't connect to my MQTT server anymore. It only showed "error" in the app, but unfortunately didn't show any details

After exporting the config, leaving the beta, uninstalling, reinstalling the stable version and importing the config it works again as it did before.

With the new version (build 21301) my MQTT server reports issues with SSL:
```
1551816331: New connection from X.X.X.X on port 8883.
1551816331: OpenSSL Error: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
1551816331: Socket error on client <unknown>, disconnecting.
1551816341: New connection from X.X.X.X on port 8883.
1551816341: OpenSSL Error: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
1551816341: Socket error on client <unknown>, disconnecting.
1551816412: New connection from X.X.X.X on port 8883.
1551816412: OpenSSL Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
1551816412: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure
1551816412: Socket error on client <unknown>, disconnecting.
```
This works just fine with the previous build, 21201.

As MQTT server I'm using Mosquitto 1.4.8 on Ubuntu 16.04 LTS.

* **App build number**: 21301
* **Android version**: 9
* **Device**: OnePlus 6T

**Comment by binarybucks** [comment] 2019-03-06 07:18
The version updated the Paho MQTT library so likely something changed there. 
Could you post your broker config?

**Comment by binarybucks** [comment] 2019-03-06 08:14
Additionally a debug log would probbaly show more information about the issue. How to enable it is outlined in https://owntracks.org/booklet/features/android/#debug-log. Afterwards, you can send it to suppoer@owntracks.org

**Comment by przemas75** [comment] 2019-03-06 20:05
Try to change 'Common Name' to proper one or try LetsEncrypt cert for mosquitto. One of these would be solution i guess. I bet the last one.
I can confirm, i had also issues with the newer version of the app, but after putting my LE cert into mosquitto and restarting the container its ok now.
(i just need to reconfigure android client also, because new cert, previously i had self signed and had ca cret installed on android).

**Comment by ktpx** [comment] 2019-03-07 12:29
I can confirm the cert solution. I switched to a real cert (had self signed) and it works again.

**Comment by syphernl** [comment] 2019-03-07 19:56
I was using a "real" certificate with a proper FQDN CN, however:

1. The CN didn't match the hostname OwnTracks connects to (but worked fine before)
2. It's a certificate from StartCom, which isn't trusted anymore

I have now replaced it with a LetsEncrypt cert with the same hostname. 
However, since the beta on Google Play is full I cannot test whether this has resolved the issue or not. @binarybucks Is there a way to re-join the beta, even though Google Play says it's full?

**Comment by binarybucks** [comment] 2019-03-07 20:01
@syphernl didn' knew it was full but apparently it defaulted to 1000 users. I've raised the limit, could you try to join again? 

From my testing, self signed certs still work, but Paho 1.2.1 apparently validates that the CN matches the hostname which actually isn't a bad thing. I'm rather suprised that it didn't before.

**Comment by syphernl** [comment] 2019-03-08 08:11
@binarybucks Wow 1000 beta users, that's nice :slightly_smiling_face:  
I was able to get back in, update to the latest version and can confirm that it is working now (that is: with my new certificate that matches the hostname). 

I guess it's a good thing that the CN is being verified, otherwise anyone could inject any other certificate (with trusted CA certificates installed to the device) to eavesdrop on the traffic.

**Comment by binarybucks** [comment] 2019-03-08 08:14
I was surprised by the number of testers myself. Glad it is working as expected now. 

Thanks for uncovering that change in behavior. I’ll add a warning to the release notes of the public version. 

Issue will be closed as everything is working as intended.

**Closed by binarybucks** 2019-03-08 08:14 UTC
