### ISSUE TITLE
Systematic Crash on Android 6.0.1

### ISSUE THREAD

**Issue by nicolasvw** [owntracks/android#438] opened 2017-01-10 15:12 UTC
I'm observing a systematic crash of the app on android 6.0.1, both Google Play and 1.1.6 (current Google Play beta) versions have this behavior.

On first run (or after clearing storage and forcing stop), the wizard is displayed requesting the extra permission and asking for public/private MQTT or HTTP, I go through it selecting either private HTTP or private MQTT (selecting Public MQTT does not display settings so crash is immediate).

When on the settings screen following the wizard, no matter if I configure it or not, launching the app again (or clicking the top left "back arrow") produces a systematic crash.

If configured at the previous step, the notification shows current location correctly and a click on the "report" action integrated in the notification actually sends an update to the topic. Clicking the notification causes a crash.

On the server side I'm using mosquitto-1.3.5 (tested with and without SSL, same behavior).

**Comment by binarybucks** [comment] 2017-01-12 16:21
The issue is likely a bug in the Google Maps library on Android 6. 
There is currently no fix but a workaround that I will ship with the next version.

**Comment by nicolasvw** [comment] 2017-01-12 16:38
Further details on this issue.

Running debug (using HEAD revision from Github) on my phone (Sony Xperia M4 Aqua), I get the stacktrace below when the crash happens.

It looks as if this could be a case of [1] related to the use of MapView. Tracking it down, it appears to trigger on line 172 of org.owntracks.android.ui.map.MapActivity. (i.e. binding.mapView.onCreate(savedInstanceState);)

I've tried to fix proposed in comments 16 and 36 of [1] (i.e. setting  android:hardwareAccelerated="true" in the manifest, both for application and MapActivity activity), didn't help.

[1] https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.owntracks.android.debug, PID: 10390
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.owntracks.android.debug/org.owntracks.android.ui.map.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2461)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521)
                      at android.app.ActivityThread.access$900(ActivityThread.java:150)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5517)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
                      at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
                      at android.view.SurfaceView.init(SurfaceView.java:207)
                      at android.view.SurfaceView.<init>(SurfaceView.java:187)
                      at maps.V.x.<init>(Unknown Source)
                      at maps.V.v.<init>(Unknown Source)
                      at maps.D.u.<init>(Unknown Source)
                      at maps.D.u.a(Unknown Source)
                      at maps.ad.ae.a(Unknown Source)
                      at maps.ad.t.a(Unknown Source)
                      at maps.ad.R.a(Unknown Source)
                      at xx.onTransact(:com.google.android.gms.DynamiteModulesB:66)
                      at android.os.Binder.transact(Binder.java:387)
                      at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
                      at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
                      at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
                      at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
                      at com.google.android.gms.maps.MapView$zzb.zzIL(Unknown Source)
                      at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
                      at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                      at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                      at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                      at org.owntracks.android.ui.map.MapActivity.onCreate(MapActivity.java:173)
                      at android.app.Activity.performCreate(Activity.java:6285)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2414)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5517) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by binarybucks** [comment] 2017-01-12 16:40
That's the issue that I had in mind, yes. At least you saved me the hassle of shipping a not working workaround.

**Comment by binarybucks** [comment] 2017-01-15 15:37
Please test with 11604 from the beta channel.

**Comment by binarybucks** [comment] 2017-01-16 12:49
android:hardwareAccelerated="true" does indeed not help. 
We will have to wait for a better fix for this as I'm not willing to move everything to a MapFragment.

**Closed** 2017-07-21 13:53 UTC
Labels: bug
