### ISSUE TITLE
Latest Android version doesn't want to accept my CA.

### ISSUE THREAD

**Issue by skorokithakis** [owntracks/android#339] opened 2016-03-25 18:20 UTC
I was using OwnTracks for Android and it worked perfectly until the latest update. Now, it refuses to connect, with "CertPathValidatorException: Trust anchor for certification path not found". Is OwnTracks expecting to find the CA cert in the system store? I'm adding the CA that used to work and it fails.

**Comment by binarybucks** [comment] 2016-03-25 18:21
did you add the certificate again via the file chooser after installing the update?

**Comment by skorokithakis** [comment] 2016-03-25 18:22
Yes, the CA cert and the .p12 private key for me. It auto-filled the password.

**Comment by binarybucks** [comment] 2016-03-25 18:43
can you please try to unset both and only connect with ca cert set? 
No need to fully connect, but just to check if the CertPathValidatorException still occurs

**Comment by skorokithakis** [comment] 2016-03-25 18:45
Yes, it still happens.

**Comment by binarybucks** [comment] 2016-03-25 18:47
could you please send the host, port and ca crt of you broker to support@owntracks.org? 
I'll try to connect and see if I can reproduce the issue.

**Comment by skorokithakis** [comment] 2016-03-25 18:48
The message only changes if I install it as a system CA. Sure, I'll email you now.

**Comment by blocke** [comment] 2016-03-25 18:49
MotoX running Android 6.0 (February 1, 2016).

It will not accept any certificate authority certificates I try to load directly into the app's Security settings. I uninstalled the app and reinstalled to clear all settings and the problem persists.

OwnTracks was working fine with the same certificate authority certificate before the most recent update.

**Comment by binarybucks** [comment] 2016-03-25 19:08
@skorokithakis So the certificate works if you import it into the system store? 
That's in contrast to what @blocke reports

Besides that, I cannot connect to your broker with the CA.crt you provided using mosquitto_sub either.

**Comment by skorokithakis** [comment] 2016-03-25 19:35
Yes, you need a client certificate. If you get "handshake failed", you've passed the bug.

**Comment by binarybucks** [comment] 2016-03-25 19:35
indeed. Bug found and fix is en route.

**Comment by blocke** [comment] 2016-03-25 19:36
I did not try importing into the system CA as Android causes an obnoxious notification about it.

**Comment by binarybucks** [comment] 2016-03-25 19:46
Could you report back if the issue is fixed in 0.6.09 please? 
I've just submitted it to Google Play, so it should be ready to install in the next hours.

**Comment by blocke** [comment] 2016-03-25 20:46
It appears to be working now. I added a CA cert within the app and I'm now able to connect to my mqtt broker again.

Thanks for fixing this so quickly.

**Comment by Bretos** [comment] 2016-03-27 08:32
That's pretty interesting, after upgrading to `0.6.9` I had to import CA into Android, or otherwise Owntracks app would not accept it, giving me the error
`Cannot import certificate to internal storage`.

**Comment by binarybucks** [comment] 2016-03-27 08:35
What Android version are you using? Do you have space left on the internal
storage partition? From were did you try to import it?

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 27 Mar 2016, at 10:33, Bretos <notifications@github.com> wrote:

That's pretty interesting, after upgrading to 0.6.9 I had to import CA into
Android, or otherwise Owntracks app would not accept it, giving me the error
Cannot import certificate to internal storage.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/339#issuecomment-202015203>

**Comment by Bretos** [comment] 2016-03-27 08:38
Sorry for not including such crucial info in my previous post. Let me fix it now.

I've tested owntracks with the same mqtt broker (the same instance) on both:

LG e610 running Android 4.4.4 with owntracks 0.6.9

LG Nexus 5 running latest nightly cyanogenmod, so Android 6.0.1

And on both phones I get the same error. On both of them, after importing CA, it starts to work. (with that ugly Android warning notification)

**Comment by netwomble** [comment] 2016-03-28 21:17
I'm getting the "Cannot import certificate to internal storage" error and CertPathValidatorException.

Version is 0.6.9, but latest change log says that this bug has been fixed.
Samsung Galaxy S6. Android 5.1.1

My MQTT server is not publicly accessible, but everything was working fine before Easter.

**Comment by binarybucks** [comment] 2016-03-28 21:30
From were did you try to import the crt with the file chooser?

On 28 Mar 2016, at 23:17, netwomble <notifications@github.com> wrote:

I'm getting the "Cannot import certificate to internal storage" error and
CertPathValidatorException.

Version is 0.6.9, but latest change log says that this bug has been fixed.
Samsung Galaxy S6. Android 5.1.1

My MQTT server is not publicly accessible, but everything was working fine
before Easter.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/339#issuecomment-202583909>

**Comment by netwomble** [comment] 2016-03-29 08:02
Hi, I copied the certificate to a directory on the phone's emulated sdcard called "certs" and then tried to add it from there using the Samsung file browser.

**Comment by netwomble** [comment] 2016-03-31 08:28
Importing the CA into the android certificate store seems to have worked. However I am still happy to do some debugging on the application importing if you need any more information.

**Comment by binarybucks** [comment] 2016-04-03 14:33
The next version (0.6.11) should fix the issue. Please report back if the issue is now solved.

**Closed by binarybucks** 2016-04-03 14:33 UTC
Labels: bug
