### ISSUE TITLE
Owntracks closes on android

### ISSUE THREAD

**Issue by ultimase** [owntracks/android#738] opened 2019-09-17 18:45 UTC
Set up everything and works through home assistant well. But for some reason the owntracks program doesn't seem to be persistent. At times it works perfectly, at times it seems to close on it's own, leaving the user stuck hours behind.

**Comment by binarybucks** [comment] 2019-09-17 18:46
Please fill out the issue template to provide information about the used versions and your device

**Comment by ultimase** [comment] 2019-09-17 18:50
Well I apologize, let me take a look at that and the android link that was a part of that, I should have done that before posting. I'll be back to either close or update with all the details.

**Comment by markrennie71** [comment] 2019-10-30 19:12
I've started to notice this as well

**Comment by NeuzNL** [comment] 2019-11-05 23:41
I have the same issue, hope owntracks will fix this soon

**Comment by growse** [comment] 2019-11-05 23:59
Without any details of device, OS version and debug log, it's difficult to make any judgement about whether this is something that's fixable with the app, or is caused by something outside the app's control.

Closing until more details are provided.

**Closed by growse** 2019-11-05 23:59 UTC
