### ISSUE TITLE
Http error: EHOSTUNREACH (No route to host)

### ISSUE THREAD

**Issue by slamdown251** [owntracks/android#1295] opened 2022-09-22 18:47 UTC
* **App build number**: 20410000
* **Android version**: 11
* **Device**: Realme X2 Pro
* **Installation source**: F-Droid

Hello,
I want to use the Owntracks app in combination with the home automation solution FHEM and the module "livetracking". The module provides a server endpoint to which the app can connect to. My setup is as follows: I have a nginx reverse proxy installed with certificates from Lets Encrypt for https, the endpoint is secured through basic authentication. The proxy routes the request to the specified endpoint. This works fine when I trigger the endpoint through a normal browser GET-request over the external adress "https://adresspart1.adresspart2.myfritz.net/fhem/osmand". But when I enter the adress in the http settings in the Owntracks app in the form "https://user:password@adresspart1.adresspart2.myfritz.net/fhem/osmand", I always get the following error in the log:

`2022-09-22 20:06:16.843 E MessageProcessor: Message delivery failed. queueLength: 1, messageId: 1663869974211-6a4ef9
2022-09-22 20:06:16.845 W MessageProcessor: Error sending message. Re-queueing
2022-09-22 20:06:16.859 I MessageProcessor: Waiting for 1 s before retrying
2022-09-22 20:06:20.356 E MessageProcessorEndpointHttp: HTTP Delivery failed 
java.net.ConnectException: Failed to connect to adresspart1.adresspart2.myfritz.net/IPV6ADRESS:443
	at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:133)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:178)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:643)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:140)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:172)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
	at okhttp3.internal.connection.RealCall.execute(SourceFile:42)
	at org.owntracks.android.services.MessageProcessorEndpointHttp.sendMessage(SourceFile:305)
	at org.owntracks.android.services.MessageProcessor.lambda$sendAvailableMessages$0(Unknown Source:2)
	at org.owntracks.android.services.MessageProcessor.$r8$lambda$DontKnowWhatThisIs(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessor$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.net.ConnectException: failed to connect to adresspart1.adresspart2.myfritz.net/IPV6ADRESS (port 443) from /IPV6ADRESS (port 41920) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
	at libcore.io.IoBridge.connect(IoBridge.java:134)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Unknown Source:5)
	at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:74)
	... 21 more
Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
	... 31 more`

Has someone maybe encountered a similar problem or can say where the problem is located? Thanks for your help.

**Comment by growse** [comment] 2022-09-23 20:39
Are you adding the credentials in the URL rather than using the username/password fields under "Identification" in the settings?

What's `IPV6ADRESS` doing in the error message? That doesn't seem to be part of the URL that you've configured. Is it significant?

**Comment by slamdown251** [comment] 2022-09-23 20:56
I've tried both options, setting the username + password in the url and setting it in the username + password fields under "Identification", same result.
Yes, the IPV6 adress is always shown there at this location in the log.

**Comment by growse** [comment] 2022-09-26 10:22
What's interesting is that you're not getting a timeout (which is what I'd expect if the device thought it knew how to connect to the address, but just can't SYN/ACK), but a `No route to host`. Your device has resolved that DNS name to an IPv6 address and then doesn't know how to route to it. 

Is this on Wifi or mobile network? Does the DNS name also have an A record for an IPv4 address? Which browser are you trying to fetch the URL from? What score do you get on https://ipv6-test.com/ ?

I'm also trying to remember a weird phenomenon where some Android sometimes completely flake out for IPv6 connectivity. It only happens on some networks and certain devices, under mysterious conditions, but it can lead to connections to IPv6-only services failing as it temporarily loses its own IPv6 connectivity.

**Comment by slamdown251** [comment] 2022-09-26 18:06
I get the error on Wifi and on mobile network. Yes, an A record for the DNS name exists. I use Firefox on my mobile phone and on my laptop and can reach the endpoint without problems over Wifi and mobile network. I've also tried to install the Owntracks app on another Samsung phone and got the same error, `No route to host`.

**Comment by slamdown251** [comment] 2022-09-27 18:49
Yes thank you, mail is sent.

**Comment by growse** [comment] 2022-09-29 10:45
Thanks for the mail.

I notice that your DNS name has both an AAAA record and an A record. When trying to telnet to the IPv6 address on the AAAA record, I get a timeout on both ports 80 and 443. Telnetting to the IPv4 address on 80/443 works fine. Similarly ICMP to the IPv4 address works, but fails on the IPv6. 

You can try this yourself on a looking glass site (e.g. https://www.cogentco.com/en/looking-glass)

I suspect the issue is that Android is resolving the name to the AAAA record (which exists), and then is failing to connect. Why it's giving "no route" rather than timeout is not clear, but I'd suggest that you might want to double-check that your endpoint is listening on IPv6.

**Closed** 2022-09-30 12:15 UTC
Labels: needs-more-info
