### ISSUE TITLE
allow TLS-CA-pinning

### ISSUE THREAD

**Issue by Finkregh** [owntracks/android#406] opened 2016-09-11 15:19 UTC
It would be super nice if the client would pin the brokers' CA-cert. That way you would not have to add a CA to android itself (and get these stupid warnings...)

user-flow:
1. enter brokers' details
2. app connects, getting the CAs cert
3. app shows user: this is the cert, trust forever or something?
4. user says yes and cert is saved inside app

**Comment by binarybucks** [comment] 2016-09-11 15:25
That isn't going to work, because the Paho MQTT library doesn't really give us access to socket, etc so implementing that flow will be incredible difficult. 

Would you be satisfied with a text field or config key were you can import the cert fingerprint that you trust?

**Comment by Finkregh** [comment] 2016-09-11 16:21
hmm, perhaps via a qr-code? Which i could also create on the server?...
Dunno :-o

Should i create a request at the mqtt-lib you are using?

**Comment by binarybucks** [comment] 2016-09-12 20:19
Well, you can just copy paste the fingerprint it into the config file or soon create a config file QR code and import that. 

Please don't submit an issue for the Paho library. It's not a bug from their side, the code is just very far away from any GUI code.

**Comment by binarybucks** [comment] 2017-05-15 14:37
This is partly implemented by importing a custom CA cert which creates a new keystore outside of Androids control. 
It is the preferred way as other methods such as pinning the public key is generally error prone depending on the implementation (see https://www.synopsys.com/blogs/software-security/ineffective-certificate-pinning-implementations/)

**Closed by binarybucks** 2017-05-15 14:37 UTC
Labels: enhancement
