### ISSUE TITLE
Crash during notification update

### ISSUE THREAD

**Issue by travisghansen** [owntracks/android#420] opened 2016-10-19 15:41 UTC
With the most recent update as soon as a beacon is detected owntracks app crashes.  I know at a minimum the mqtt message is getting sent as I can see it hit my backend.

Thanks!

**Comment by binarybucks** [comment] 2016-10-19 16:07
Which app version are you using? If it is 11301, please update to11302.

Otherwise I've not yet received a crash report for anything that could
cause this.

**Comment by travisghansen** [comment] 2016-10-19 19:43
It's 11302.  The issue wasn't present for me *until* this most recent upgrade.

**Comment by binarybucks** [comment] 2016-10-19 19:46
It probably was, build 2 changed nothing else of importance. I've however
found another issue that could cause a crash. There will be an update
tomorrow.

Am 19.10.2016 um 21:43 schrieb Travis Glenn Hansen <notifications@github.com
>:

It's 11302. The issue wasn't present for me *until* this most recent
upgrade.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/420#issuecomment-254919353>,
or mute the thread

**Comment by travisghansen** [comment] 2016-10-20 04:56
Sounds good I'll try it out when it hits.  Thanks!

**Comment by binarybucks** [comment] 2016-10-20 06:31
Fixed in 1.1.4 (available shortly). 
Please reopen if the issue is not fixed.

**Closed by binarybucks** 2016-10-20 06:31 UTC
