### ISSUE TITLE
Select location malfunction

### ISSUE THREAD

**Issue by chusweb** [owntracks/android#764] opened 2019-11-10 17:38 UTC
* **App build number**: 2.1.3 (21301)
* **Android version**: 9   
* **Device**: Huawei P20 Pro

Trying to add a Region, if you select "Select location" icon, the screen open and close immediately, making impossible to use it.

**Comment by binarybucks** [comment] 2019-11-11 08:58
The place picker library got disabled due to changes regarding API usage. The issue is fixed in the next release.

**Closed by binarybucks** 2019-11-11 08:58 UTC
