### ISSUE TITLE
App won't even start

### ISSUE THREAD

**Issue by MenfisRaynes** [owntracks/android#1689] opened 2024-04-24 18:16 UTC
My App of Owntracks stoppt working completely since the last update. The App won't even start. Directly shuts down.  :-(

* **App build number**: 2.5.0 Beta (updated: 15.04.2024)
* **Android version**: Unknown - only shows EMUI 12.0.0.142 - No android version shown
* **Device**: Huawaei Mate 20 Pro
* **Installation source**: Google Play Store

**Comment by jpmens** [comment] 2024-04-24 18:23
Possibly a duplicate of https://github.com/owntracks/android/issues/1683

**Comment by growse** [comment] 2024-04-25 09:50
Dupe.

**Closed by growse** 2024-04-25 09:50 UTC
