### ISSUE TITLE
ActivityImport.java line 120

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#177] opened 2015-04-24 16:06 UTC
#### in org.owntracks.android.activities.ActivityImport.extractPreferences

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/553a6a085141dcfd8f90db9f](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/553a6a085141dcfd8f90db9f)

**Comment by binarybucks** [comment] 2015-06-09 15:04
duplicate of #178

**Closed by binarybucks** 2015-06-09 15:04 UTC
